version: '3'

services:
  smoobu_automation:
    image: pelyform/smoobu_automation:v1
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - smoobu_automation_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/server-configuration/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ec2-user/data/certbot/conf/live:/etc/letsencrypt/live:ro
      - /home/ec2-user/data/certbot/conf/archive:/etc/letsencrypt/archive:ro
      - /home/ec2-user/data/certbot/conf/renewal:/etc/letsencrypt/renewal:ro
    networks:
      - smoobu_automation_network
    restart: unless-stopped

networks:
  smoobu_automation_network:
    driver: bridge

